### ISSUE TITLE
ox_lib progressbar integration

### ISSUE THREAD

**Issue by rohKane** [rohKane/progressbar#3]
so in ox_lib/resource/interface/client/progress.lua find **function lib.progressBar(data)** replace that whole function code with mine here

```
function lib.progressBar(data)
    while progress ~= nil do Wait(0) end

    if not interruptProgress(data) then
            exports['progressbar']:Progress({
            name = "random_task",
            duration = data.duration,
            label = data.label,
            useWhileDead = false,
            canCancel = true,
            controlDisables = {
                disableMovement = false,
                disableCarMovement = false,
                disableMouse = false,
                disableCombat = false,
            },
         }, function(cancelled)
            if not cancelled then
                -- finished
                --SendNUIMessage({
                    --action = 'progress',
                    --data = {
                        --label = data.label,
                        --duration = data.duration
                        --duration = -100
                    --}
                --})
                progress = nil
            else
                -- cancelled
                print("omg")
                -- Reset progress whether it's finished or cancelled
                progress = false
                Citizen.Wait(1000)
                progress = nil
            end
         end)

        return startProgress(data)
    end
end
```
let me know if it is working or not.

_Originally posted by @rohKane in https://github.com/rohKane/progressbar/issues/1#issuecomment-1874868733_

**Comment by rohKane** [comment]
> works fine but it breaks some functions such as busy status and all since the progressbar is running from somewhere else :(

Try this and let me know if it work or not thank.
```

function lib.progressBar(data)
    while progress ~= nil do Wait(0) end

    if not interruptProgress(data) then
            playerState.invBusy = true
            exports['progressbar']:Progress({
            name = "random_task",
            duration = data.duration,
            label = data.label,
            useWhileDead = false,
            canCancel = true,
            controlDisables = {
                disableMovement = false,
                disableCarMovement = false,
                disableMouse = false,
                disableCombat = false,
            },
         }, function(cancelled)
            if not cancelled then
                -- finished
                --SendNUIMessage({
                    --action = 'progress',
                    --data = {
                        --label = data.label,
                        --duration = data.duration
                        --duration = -100
                    --}
                --})
                progress = nil
            else
                -- cancelled
                print("omg")
                -- Reset progress whether it's finished or cancelled
                progress = false
                Citizen.Wait(1000)
                progress = nil
                playerState.invBusy = false
            end
         end)

        return startProgress(data)
    end
end

```

**Comment by rohKane** [comment]
no worries, glad it worked.

**Comment by gitgaming21** [comment]
so with this if you hit x to stop the prograss it will not stop it and the ui will stay on as well

**Comment by rohKane** [comment]
> so with this if you hit x to stop the prograss it will not stop it and the ui will stay on as well

press ESC bro

**Comment by rohKane** [comment]
> > so with this if you hit x to stop the prograss it will not stop it and the ui will stay on as well
> 
> if IsControlJustPressed(0,73) then TriggerEvent('progressbar:client:cancel') end
> 
> put this inside your progressbar thread

Thanks for this but press ESC will work just fine

**Comment by dae4100** [comment]
> > so with this if you hit x to stop the prograss it will not stop it and the ui will stay on as well
> 
> if IsControlJustPressed(0,73) then TriggerEvent('progressbar:client:cancel') end
> 
> put this inside your progressbar thread

when you hit x it removes the item and cancels

**Comment by dae4100** [comment]
if IsControlJustPressed(0,73) then
                    TriggerEvent('progressbar:client:cancel')
                    wasCancelled = true
                    end 
                    
                    
                    this fixed it for everyone who needs it

**Comment by EppuCLUB** [comment]
Its not working just saying 
![image](https://github.com/rohKane/progressbar/assets/144498221/510c482c-c570-4e44-9762-4864c2a7fe28)

**Comment by rohKane** [comment]
don't rename the script if you do it correctly it will work xD

**Comment by EppuCLUB** [comment]
bruh i havent rename the script your script isint even working with the ox_lib?

**Comment by rohKane** [comment]
Install it again m8

**Comment by EppuScripts** [comment]
yo roh is it possible to do the same progresbar with the circle one?

**Comment by rohKane** [comment]
Ofc change the syntax to match it

**Comment by promiiss033** [comment]
could you do the same for qb-notify, so it overrides the ox lib notfiy?

**Comment by myhremanden** [comment]
<img width="940" height="103" alt="Image" src="https://github.com/user-attachments/assets/5e535772-9506-4932-aa0e-fdc07d8b36ec" />

Anyone? Please help 😃
