### ISSUE TITLE
Progressbar Issue with harness Function

### ISSUE THREAD

**Issue by ChrizsTTV** [rohKane/progressbar#5]
Hey, I currently have the problem that my jim-mechanic Harness isn't working with your progressbar. Its the only Issue I found so I figured maybe you could help me with it. The Progressbar shows up but the Event after it isn't executed. I cant put on my harness and so stuff. I tried using the provided Templates but even with that the complete harness and seatbelt function is completely broken.

**Comment by rohKane** [comment]
If you set it up correctly it will work.

**Comment by rohKane** [comment]
Try downloading the original QB progressbar from QBcore and replacing it with mine to see if it works or not. If it still doesn't work, ask for help on the QBcore progressbar because all I did to the progressbar was change its appearance.

**Comment by ChrizsTTV** [comment]
I manually changed the jim-mechanic function because somehow some of the build in progressbar functions dont work with yours even tho its just a replacement. It was just a minor change tho. To Be Fair, Jim-mechanic has some weird written progressbar function with harness prop and stuff.
