### ISSUE TITLE
help switching progress pls i cant seme to getr it..

### ISSUE THREAD

**Issue by poolshark120502** [rohKane/progressbar#6]
![image](https://github.com/rohKane/progressbar/assets/72841575/14cd0eb7-448b-4d6f-a5a8-bcc83516224b)

**Comment by rohKane** [comment]
What do you mean?

**Comment by poolshark120502** [comment]
![image](https://github.com/rohKane/progressbar/assets/72841575/1805a25a-8b7a-4037-986a-e1907f5252cc)
im sorry i got it i was running off 0 sleep that night..
